rvm: 
  - 1.9.3
language: 
  - ruby
env: 
global: 
- secure: "KFJ1fcMotPZ/IOhUMkpOu2p1Rf+yNZfR9XVC8gmDR5/xf8LsenLE5k9io3x2\n60xISaGPkGJJhUvo6oEXOJ0jSSww/qkB9uUMPqil4CWXterhpekFbPZjTnXs\nkRBn5tLXFeUcX93KIKYMr3azcw4pvqXyt4aI76O00E7gMJFwAdg="

before_script: 
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bundle exec rake serverup
script: 
- bundle exec rake test:all
after_script: 
- bundle exec rake serverdown
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:notebook2reveal.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
