development:
  sessions:
    default:
      database: wddb_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: wddb_test
      hosts:
        - localhost:27017

production: 
  sessions:
    default:
      database: wddb_prod
      hosts:
        - localhost:27017
